### CREATE a Customer

# @name create a new customer
POST http://localhost:8080/api/v1/customers
Accept: application/json
Content-Type: application/json

{
  "firstName": "Rose",
  "lastName": "Mari",
  "email": "rose.mari@gmail.com",
  "password": "1234",
  "street": "Malarvagen",
  "city": "Lund",
  "zipcode": "34326"
}

### Get Customer by Id

# @name get customer by id
GET http://localhost:8080/api/v1/customers/1
Accept: application/json

### Update Customer by Id

# @name update a customer by id
PUT http://localhost:8080/api/v1/customers/2
Accept: application/json
Content-Type: application/json

{
  "firstName": "Rose",
  "lastName": "Mari",
  "email": "rose.mari@gmail.com",
  "password": "1234",
  "street": "Malarvagen",
  "city": "Malmo",
  "zipcode": "34326"
}

### CREATE a Product

# @name create a product
POST http://localhost:8080/api/v1/products
Accept: application/json
Content-Type: application/json

{
  "name": "Laptop",
  "price": 13000.00,
  "categoryId": 1
}

### GET All

# @name get all products
GET http://localhost:8080/api/v1/products
Accept: application/json

### GET By Name

# @name search by name
GET http://localhost:8080/api/v1/products/search/name?name=Mouse
Accept: application/json

### CREATE a Category
POST http://localhost:8080/api/v1/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Toys"
}

### GET All Categories

# @name get all categories
GET http://localhost:8080/api/v1/categories
Accept: application/json